INSERT INTO planets (name, description, diameter, type)
  VALUES ('Mercury', 'Closest planet to the Sun', 28.5, 'Rocky');

INSERT INTO planets (name, description, diameter, type)
  VALUES ('Venus', '', 56.5, 'Rocky');

INSERT INTO planets (name, description, diameter, type)
  VALUES ('Earth', 'Our home', 75.5, 'Rocky');

INSERT INTO planets (name, description, diameter, type)
  VALUES ('Mars', 'The red planet', 60.5, 'Rocky');

INSERT INTO planets (name, description, diameter, type)
  VALUES ('Jupiter', 'The big boy in the Solar system', 500.5, 'Gaseous');

INSERT INTO planets (name, description, diameter, type)
  VALUES ('Saturn', 'Nice rings!', 400.5, 'Gaseous');

INSERT INTO planets (name, description, diameter, type)
  VALUES ('Uranus', 'Cold', 300.5, 'Gaseous');

INSERT INTO planets (name, description, diameter, type)
  VALUES ('Neptune', 'Colder', 150.5, 'Gaseous');

INSERT INTO planets (name, description, diameter, type)
  VALUES ('Pluto', 'Coldest', 10.5, 'Gaseous');